// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGc3BbvyqdLjcJbN_gs6EiOzoQFiv09GA',
    appId: '1:1024418225067:android:b7002f24162d5936eb50ee',
    messagingSenderId: '1024418225067',
    projectId: 'task-d683e',
    storageBucket: 'task-d683e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1C9dRpwajn7_Q0dcnnT5zyWEniP0XaJ4',
    appId: '1:1024418225067:ios:34a927f0ae5da12beb50ee',
    messagingSenderId: '1024418225067',
    projectId: 'task-d683e',
    storageBucket: 'task-d683e.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZlkgcjRyA1Ni278CRW4hhdiv9zvDYMaw',
    appId: '1:1024418225067:web:440700fabf5fbdf6eb50ee',
    messagingSenderId: '1024418225067',
    projectId: 'task-d683e',
    authDomain: 'task-d683e.firebaseapp.com',
    storageBucket: 'task-d683e.appspot.com',
    measurementId: 'G-W53YHMZTL3',
  );

}